#!/bin/bash
#
# Jacek Lysiak <jacek.lysiako.o.at.gmail.com>
#
# Installation script.
# Copy tools into hidden dir @ your home.
#

old=$PWD

dir=".nn4omtf_cli"
cd ~
mkdir -p $dir
cd $dir
echo "Copying tool files:"

cp -v $old/omtf* .
exp='PATH=$PATH:'${PWD}
if [ -z $(cat ~/.bashrc | grep "${PWD}") ]; then
  echo "Exporting PATH: $PWD$"
  echo $exp >> ~/.bashrc
  echo "export PATH" >> ~/.bashrc
else
  echo "$PWD path already exported!"
fi

echo "Done!"

cd $old

