#!/usr/bin/env python3
# -*- coding: utf-8 -*- 

import sys
import platform
import argparse
import os
import time

import nn4omtf
from nn4omtf.dataset import OMTFDataset

desc="""
Command line tools for nn4omtf.
This script handles operations on datasets.
"""


class ACTION:
    ROOT2NUMPY = "root2np"
    CREATE = "create"
    SHOW = "show"
    ADD = "add"


def show_summary(path):
    dataset = OMTFDataset.load(path)
    print(dataset)


def create_dataset(**kw):
    del kw['action']
    files = kw['file']
    del kw['file']
    v = kw['v']
    del kw['v']
    dataset = OMTFDataset(**kw)
    dataset.add_npz_to_dataset(files, v)
    dataset.save()
    

def convert(flist, dest, verbose):
    """Convert list of ROOT dataset files into Numpy dataset."""
    # I know... Importing here is not beautiful but...
    if verbose:
        print("Importing ROOT's stuff...")
    nn4omtf.import_root_utils()
    if verbose:
        print("Creating directory: " + dest)
    os.makedirs(dest, exist_ok=True)
    
    total = len(flist)
    cnt = 1
    time_start = time.time()
    time_last = time_start
    if verbose:
        print("Starting conversion of {} files".format(total))
        for f in flist:
            print("> " + f)

    for f in flist:
        if verbose:
            print("Converting {} of {}: {}".format(cnt, total, f))
        data = nn4omtf.root_utils.load_root_dict(f)
        name = data[1]['name']
        sign = data[1]['sign']
        pt_code = data[1]['val']
        x = nn4omtf.root_utils.root_to_numpy(name, sign, pt_code, data[0])
        path = os.path.join(dest, "{}_{}_{}.npz".format(name, sign, pt_code))
        if verbose:
            print("Saving converted data as " + path)
        nn4omtf.utils.save_dict_as_npz(path, **x)
        now = time.time()
        if verbose:
            print("Done in %.2f sec." % (now-time_last))
            print("Elapsed from start: {}' {}''".format(int((now - time_start) // 60), int(now - time_start) % 60))
        cnt += 1
        time_last = now
    if verbose:
        print("Conversion finished!")


def add_files(path, files, v):
    dataset = OMTFDataset.load(path)
    dataset.add_npz_to_dataset(files, v)
    dataset.save()


def take_action(action, FLAGS):
    if action == ACTION.SHOW:
        show_summary(FLAGS.dir)
    elif action == ACTION.CREATE:
        create_dataset(**dict(FLAGS._get_kwargs()))
    elif action == ACTION.ROOT2NUMPY:
        convert(FLAGS.data, FLAGS.dest, FLAGS.verbose)
    elif action == ACTION.ADD:
        add_files(FLAGS.dir, FLAGS.file, FLAGS.v)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=desc)
    subparsers = parser.add_subparsers(title="Actions", description="Actions to perform", dest="action")

    show = subparsers.add_parser(ACTION.SHOW, help="Look up for dataset object and show summary.")
    show.add_argument("dir", nargs="?", default=".", help="Dataset object directory")

    create = subparsers.add_parser(ACTION.CREATE, help="Create new dataset from *.npz files.")
    create.add_argument("-c", "--compress", action="store_true", help="Compress TFRecords")
    create.add_argument("-v", action="store_true", help="Verbose mode!")
    create.add_argument("--events_frac", metavar="val", type=float, default=1, help="Fraction (0-1) of all events in each file which will be saved in TFRecords.")
    create.add_argument("--train_frac", metavar="val", type=float, default=0.7, help="Fraction (0-1) of saved events from each file which will be saved in train dataset.")
    create.add_argument("--valid_frac", metavar="val", type=float, default=0.15, help="Fraction (0-1) of saved events from each file which will be saved in validation dataset.")
    create.add_argument("name", help="Dataset name")
    create.add_argument("path", help="Destination path")
    create.add_argument("file", nargs="*", help="*.npz files which should be taken to dataset")

    add = subparsers.add_parser(ACTION.ADD, help="Add examples from *.npz files into existing dataset.")
    add.add_argument("-v", action="store_true", help="Verbose mode!")
    add.add_argument("dir", help="Dataset object directory")
    add.add_argument("file", nargs="+", help="*.npz files which will be added into dataset")


    r2n = subparsers.add_parser(ACTION.ROOT2NUMPY, help="Convert ROOT datasets to Numpy arrays. ROOT environment requred!")
    r2n.add_argument("-v", "--verbose", action="store_true")
    r2n.add_argument("dest", help="Destination directory")
    r2n.add_argument("data", nargs="+", help="Source directories with ROOT datasets.")
    
    FLAGS, unparsed = parser.parse_known_args()
    
    if FLAGS.action is None:
        parser.print_help()
    else:
        take_action(FLAGS.action, FLAGS)
