#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-
# 
# author: Jacek Łysiak <jacek.lysiako.o.at.gmail.com>
#
# Command line client for OMTFNN object.
#
# =================================================

import sys
import platform
import argparse


if __name__ == "__main__":
#    print("HELLO")
#    print(sys.version)
#    print(platform.python_version())

    parser = argparse.ArgumentParser()
    parser.add_argument("echo")
    args = parser.parse_args()
    print(args.echo)
