#!/usr/bin/env python3
# -*- coding: utf-8 -*- 
"""
    Copyright(C) 2018 Jacek Łysiak
    MIT License
"""

from nn4omtf.cli import OMTFDatasetTool


if __name__ == '__main__':
    tool = OMTFDatasetTool()
    tool.run()

